import { NeuroModule } from "@/app/types";

export const NB_MODULES: NeuroModule[] = [
  {
    id: "nb01",
    code: "NB01",
    name: "Neuroanatomy and Neurophysiology",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb01-1",
          name: "Functional Organization of Vertebrate CNS",
          credits: 3,
          graded: false,
        },
        {
          id: "nb01-2",
          name: "Neurophysiology",
          credits: 3,
          graded: true,
          weight: 100,
        },
        {
          id: "nb01-3",
          name: "Molecular and Cellular Neuroscience",
          credits: 3,
          graded: false,
        },
      ],
    },
  },
  {
    id: "nb02",
    code: "NB02",
    name: "Sensorimotor Systems",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb02-1",
          name: "Sensory Systems 1",
          credits: 3,
          graded: true,
          weight: 50,
        },
        {
          id: "nb02-2",
          name: "Sensory Systems 2",
          credits: 3,
          graded: true,
          weight: 50,
        },
        {
          id: "nb02-3",
          name: "Motor Systems",
          credits: 3,
          graded: false,
        },
      ],
    },
  },
  {
    id: "nb03",
    code: "NB03",
    name: "Cognitive Neuroscience",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb03-1",
          name: "Lecture",
          credits: 3,
          graded: true,
          weight: 100,
        },
        {
          id: "nb03-2",
          name: "Seminar",
          credits: 3,
          graded: false,
        },
      ],
    },
  },
  {
    id: "nb04",
    code: "NB04",
    name: "Neuropsychology",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb04-1",
          name: "Neuropsychology",
          credits: 3,
          graded: true,
          weight: 100,
        },
        {
          id: "nb04-2",
          name: "Methods in Neuropsychology",
          credits: 3,
          graded: false,
        },
      ],
    },
  },
  {
    id: "nb05",
    code: "NB05",
    name: "Data Analysis",
    credits: 6,
    kind: "graded",
    countsTowardFinal: true,
    group: "foundations",
    structure: {
      type: "guidedSlots",
      slots: [
        {
          id: "nb05-stats",
          label: "Statistics",
          credits: 3,
          graded: true,
          options: [
            { id: "nb05-stats-essential", name: "Essential Statistics" },
            { id: "nb05-stats-advanced", name: "Advanced Statistics" },
          ],
        },
        {
          id: "nb05-math",
          label: "Mathematics / Programming",
          credits: 3,
          graded: false,
          options: [
            { id: "nb05-math-essential", name: "Essential Mathematics" },
            { id: "nb05-math-programming", name: "Basic Programming" },
          ],
        },
      ],
    },
  },
  {
    id: "nb06",
    code: "NB06",
    name: "Advanced Methods",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "advanced",
    hint: "9 CP total required; at least 3 CP graded. Number of courses unrestricted.",
    structure: {
      type: "userAdded",
      targetCredits: 9,
      graded: true,
    },
  },
  {
    id: "nb07",
    code: "NB07",
    name: "Advanced Neuroscience",
    credits: 9,
    kind: "graded",
    countsTowardFinal: true,
    group: "advanced",
    hint: "9 CP total required; at least 3 CP graded. Number of courses unrestricted.",
    structure: {
      type: "userAdded",
      targetCredits: 9,
      graded: true,
    },
  },
  {
    id: "nb08",
    code: "NB08",
    name: "Electives",
    credits: 6,
    kind: "completion",
    countsTowardFinal: false,
    group: "electives",
    structure: {
      type: "userAdded",
      targetCredits: 6,
      graded: false,
    },
  },
  {
    id: "nb09",
    code: "NB09",
    name: "Current Research and RCR",
    credits: 3,
    kind: "completion",
    countsTowardFinal: false,
    group: "research",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb09-1",
          name: "Neurocolloquium",
          credits: 1,
          graded: false,
        },
        {
          id: "nb09-2",
          name: "Scholarly Research",
          credits: 2,
          graded: false,
        },
      ],
    },
  },
  {
    id: "nb10",
    code: "NB10",
    name: "Laboratory Rotations",
    credits: 27,
    kind: "graded",
    countsTowardFinal: true,
    group: "research",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb10-1",
          name: "Laboratory Rotation 1",
          credits: 13,
          graded: true,
          weight: 50,
        },
        {
          id: "nb10-2",
          name: "Laboratory Rotation 2",
          credits: 14,
          graded: true,
          weight: 50,
        },
      ],
    },
  },
  {
    id: "nb11",
    code: "NB11",
    name: "Master's Thesis",
    credits: 30,
    kind: "thesis",
    countsTowardFinal: false,
    group: "thesis",
    structure: {
      type: "subCourses",
      subCourses: [
        {
          id: "nb11-1",
          name: "Master's Thesis",
          credits: 30,
          graded: true,
          weight: 100,
        },
      ],
    },
  },
];
